### ISSUE TITLE
Create project gives 500 Internal Server Error

### ISSUE THREAD

**Issue by Vinai** [Vinai/magehack-voting#11]
Since the last pull it is no longer possible to create projects.

It seems to make no difference if I send the data with or without the github_url and/or hangout_url.

Attached is a screenshot with the POST request details.

![bildschirmfoto 2014-01-24 um 05 44 47](https://f.cloud.github.com/assets/72463/1992141/4c185868-84b2-11e3-8c9a-1acef2c5d75d.png)

**Comment by amacgregor** [comment]
After some digging seems that the form is no correctly passing the data please look at the following screenshot the urls are undefined even when provided 

![image](https://f.cloud.github.com/assets/212169/1994193/696a8540-84e8-11e3-821c-d414c1dfb7ac.png)

The Product controller expects an array with the input values for creating the object

**Comment by amacgregor** [comment]
Further testing I see the problem, the both url fields need to be valid urls but if they are not the frontend is not throwing any errors

**Comment by Vinai** [comment]
Will look at it after class today.

**Comment by amacgregor** [comment]
Additionally it seems that the project object that the form passes has extra data which causes an error when creating the project. If possible could you please make sure that you only post a project with the following values:

title, description, github_url, hangout_url

**Comment by Vinai** [comment]
Fixed in 178e4be
