### ISSUE TITLE
Updating projects with a github_url property cause an HTTP 500 Internal Server Error Response

### ISSUE THREAD

**Issue by Vinai** [Vinai/magehack-voting#12]
When updating a project with a github_url property the application throws an Internal Server Error.

When I remove the github_url property from the project before sending it the updates work.

Attached is a screenshot with the PUT request details.

![bildschirmfoto 2014-01-24 um 05 48 46](https://f.cloud.github.com/assets/72463/1992165/1e309a22-84b3-11e3-96c2-ec9452a283bb.png)

**Comment by amacgregor** [comment]
Please be sure to run 

```
php artisan migrate
```

The github_url was added on a migration on my last commit.

**Comment by Vinai** [comment]
Thanks, that did it!
